import { NextResponse } from "next/server";

import { mockSummary } from "~/lib/mockData";

const formatCurrency = (value: number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);

const formatNumber = (value: number) =>
  new Intl.NumberFormat("en-US").format(value);

export async function GET() {
  const { totalValueUSD, dailyTx, openAlerts, highRiskWallets, anomalies24h } = mockSummary;

  // Create a formatted markdown summary
  const markdown = `# Wallet Guardian Summary

## Portfolio Overview

| Metric | Value |
|--------|-------|
| **Total Value** | ${formatCurrency(totalValueUSD)} |
| **Daily Transactions** | ${formatNumber(dailyTx)} |
| **Open Alerts** | ${openAlerts} |
| **High Risk Wallets** | ${highRiskWallets} |
| **Anomalies (24h)** | ${anomalies24h} |

---

## Status

${openAlerts > 0 ? `**${openAlerts} active alert(s)** require attention.` : "All systems nominal."}

${highRiskWallets > 0 ? `**${highRiskWallets} high-risk wallet(s)** under monitoring.` : "No high-risk wallets detected."}

${anomalies24h > 0 ? `**${anomalies24h} anomaly(ies)** detected in the last 24 hours.` : "No anomalies in the last 24 hours."}

---

*Generated by Assertion OS - Industrial-grade multi-chain wallet security*
`;

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
    },
  });
}






